### PR TITLE
Denraf/feature/yamltojson

### PR DESCRIPTION
**Pull request by denraf**
### Description
Adding extra modifier: yamltojson

**Fixes:** https://github.com/IBM/argocd-vault-plugin/issues/232

### Checklist
Please make sure that your PR fulfills the following requirements:
- [X] Reviewed the guidelines for contributing to this repository
- [X] The commit message follows the [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0/#summary).
- [X] Tests for the changes have been updated
- [ ] Docs have been added / updated
- [ ] Optional. My organization is added to USERS.md.

### Type of Change

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

### Other information
I have a build with these two plugins running in my test environment.
Full path to secret:
`secret: <path:path/to/yaml#secret| yamltojson  | jsonPath {.secret_key} >`

### CODE REVIEW

**Comment by teejaded** [comment]
So, in the other PR I mentioned the pipeline can pass objects.  Also jsonPath can operate on objects so the actual usage of it doesn't look much different than what you have.

```
secret: <path:path/to/yaml#secret | yamlParse | jsonPath {.secret_key} >
```

```golang
func yamlParse(params []string, input interface{}) (interface{}, error) {
	if len(params) > 0 {
		return nil, fmt.Errorf("invalid parameters")
	}
	switch input.(type) {
	case string:
		{
			var obj interface{}
			err := k8yaml.Unmarshal([]byte(input.(string)), &obj)
			if err != nil {
				return nil, err
			}
			return obj, nil
		}
	default:
		return nil, fmt.Errorf("invalid datatype %v", reflect.TypeOf(input))
	}
}
```

**Comment by denraf** [comment]
Hi @teejaded 
Looking at the k8yaml library, both the `Unmarshal` and `YAMLToJSON` functions use the same logic. `Unmarshal` just does an extra `jsonUnmarshal`. So for this implementation we can use either option, I'm fine with whatever the consensus is.

**Review by jkayani — APPROVED** [review]
Looks good to me. Thanks for your patience with getting the PR split up like this.

**Comment by werne2j** [comment]
@denraf This would be my preference https://github.com/IBM/argocd-vault-plugin/pull/237#issuecomment-977315182. Once those changes are made i'll be good to go. Thanks!

**Comment by denraf** [comment]
@werne2j Done. Thank you for the help!

**Comment by werne2j** [comment]
Im sorry @denraf could you also rename `yamltojson` to `yamlParse`. I should have been more clear. Thank you for being patient with us! 😄

**Comment by denraf** [comment]
@werne2j Done, renamed everything to `yamlParse`

**Review by werne2j — APPROVED** [review]
Thanks!

**Pull request merged**
